---
title: "groundwaterconductivity"
author: "Patrick van Beelen"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{groundwaterconductivity}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup}
knitr::opts_chunk$set(eval = FALSE, include = FALSE)
library(groundwaterconductivity)
```

## Introduction

Whereas the README.Rds file of <https://github.com/PatrickvanBeelen/groundwaterconductivity> gives you information about what you can do with the groundwaterconductivity package. This manual will show you how to do it. The method is described in a Dutch report by Stuyfzand, P. (1987). Een zeer nauwkeurige berekening van het elektrisch geleidingsvermogen, ter controle en aanvulling van wateranalyses: 2e versie. Rijswijk, KIWA. Table 3.1 of this report is used to test the calculations. The table 3.1 is shown in data/input_groundwaterconductivity.rda

If you have installed the package according to the README file typing library(groundwaterconductivity) in the R console will load the functions. The standard inputfile can be made by:

input_groundwaterconductivity \<- calculate_conductivity() save(input_groundwaterconductivity,file="input_groundwaterconductivity.rda")

If you run:

myoutputdataframe \<- calculate_conductivity(inputfilename="input_groundwaterconductivity.rda", inputstyle = "Stuyfzand",outputstyle = "minimal", celcius = 25)

The calculations will be performed and the standard LMM style inputfile is saved as "LMM_broad_input_groundwaterconductivity.rda" and the standard outputfile as "with_all_calculated_conductivity.rda". The outputstyle "minimal" converts "with_all_calculated_conductivity" into "with_calculated_conductivity.rda". You can replace input_groundwaterconductivity.rda with your own data.

If you want to incorporate the function in your own script you will need a proper data input dataframe adhering to the rules below under Data input. If a dataframe called input_groundwaterconductivity is in the Global Environment the script will ignore any input file like nofile.rda and will use input_groundwaterconductivity instead. Moreover it will not read or write any files.

input_groundwaterconductivity\<-myinputdataframe if (!"myrownames"%in%names(input_groundwaterconductivity)){ input_groundwaterconductivity\$myrownames\<-rownames(input_groundwaterconductivity) }

withconductivity=calculate_conductivity(inputfilename = 'nofile.rda',inputstyle = "broadLMM",outputstyle = "minimal",celcius=25)

conductivity\<-withconductivity %\>% select(!starts_with("x"))

\# merge myinputdataframe with the conductivity output using myrownames myoutputdataframe\<-merge.data.frame(input_groundwaterconductivity,conductivity,by="myrownames")

## Data input

The groundwater conductivity calculations require proper names and dimensions of the input parameters needed to calculate the conductivity. Table 1 below presents the name, content and dimension of the parameters needed. The first rows from rownumber to Calculated conductivity are also present in Table 3.1 of the Stuyfzand report and are used for the quality test of the calculations. Stuyfzand did not use aluminum, iron, phosphate, manganese and zinc to validate his method. The Dutch Minerals Monitoring Policy Program is using the groundwater conductivity calculations presented here for decades. This program is abbreviated to LMM in Dutch and has its own parameter names and dimensions. In most cases milligrams/liter is used except for a few differences mentioned in column LMM dimension.

Table 1 measured parameters (`Table`):

+------------+-------------------------+------------+------------+------------+
| name       | content                 | dimension  | LMM        | LMM        |
|            |                         |            |            |            |
|            |                         |            | name       | dimension  |
+:===========+:========================+:===========+============+============+
| no         | rownumber               |            | myrownames |            |
+------------+-------------------------+------------+------------+------------+
| cl         | Choride                 | mg/L       | xcl        |            |
+------------+-------------------------+------------+------------+------------+
| hco3       | Bicarbonate             | mg/L       | xhco3      |            |
+------------+-------------------------+------------+------------+------------+
| so4        | Sulfate                 | mg/L       | xso4       |            |
+------------+-------------------------+------------+------------+------------+
| no3        | Nitrate                 | mg/L       | xno3       |            |
+------------+-------------------------+------------+------------+------------+
| co3        | Carbonate               | mg/L       | xco3       |            |
+------------+-------------------------+------------+------------+------------+
| h          | pH                      |            | xhv        |            |
+------------+-------------------------+------------+------------+------------+
| na         | Sodium                  | mg/L       | xna        |            |
+------------+-------------------------+------------+------------+------------+
| k          | Potassium               | mg/L       | xk         |            |
+------------+-------------------------+------------+------------+------------+
| ca         | Calcium                 | mg/L       | ca         |            |
+------------+-------------------------+------------+------------+------------+
| mg         | Magnesium               | mg/L       | xmg        |            |
+------------+-------------------------+------------+------------+------------+
| nh4        | Ammonium                | mg/L       | xnh4       |            |
+------------+-------------------------+------------+------------+------------+
| k20        | Measured conductivity   | µS/cm      | xecv       | mS/m       |
+------------+-------------------------+------------+------------+------------+
| rk20       | Calculated conductivity | µS/cm      | ec25       | mS/m       |
+------------+-------------------------+------------+------------+------------+
| al         | Aluminum                | mg/l       | xal        | µg/L       |
+------------+-------------------------+------------+------------+------------+
| fe         | Iron                    | mg/L       | xfe        |            |
+------------+-------------------------+------------+------------+------------+
| po4        | Phosphate               | mg/L       | xpo4       | mg P/L     |
+------------+-------------------------+------------+------------+------------+
| mn         | Manganese               | mg/L       | xmn        |            |
+------------+-------------------------+------------+------------+------------+
| zn         | Zinc                    | mg/L       | xzn        | µg/L       |
+------------+-------------------------+------------+------------+------------+

Stuyfzand measured the conductivity at 20°C and expressed it in micro Siemens/centimeter. At the LMM the conductivity is determined at 25°C and is expressed in milliSiemens/meter. In fact it is measured in the field and a temperature correction is made to get the measured conductivity at 25°C. The conductivity increases at higher temperatures and Stuyfzand calculates the k20 from the conductivity kt at a given temperature t °C using: k20 = kt \* $$1+0.023 \* (20-t)$$

Hence, the calculated conductivity rk20 at 20°C can be converted to the calculated conductivity ec25 at 25°C using: ec25 = 0.1 \* rk20/ $$1-0.023 \* (25-20)$$

The data input results in a standard broad LMM style input file like LMM_broad_input_groundwaterconductivity.rda It has all the necessary input parameters mentioned in table 1. This makes it possible to check whether the input parameters are correct.

## Missing data and pH

The parameters that are not provided are set to zero except for the pH which is set to 7. The H+ concentration is also set in milligrams/liter which is equal to milliequivalents/liter since the atomic weight is 1. For clarity the H plus concentration in milliequivalents/liter is expressed in the script as h3o = 1000 \* 10\^xhv

## Data output

The data output results in a standard broad LMM style output file named with_all_calculated_conductivity.rda It has 73 parameters mentioned in table 2.

Table 2 Output headings

+----------------------+------------+---------------------------------------------------------------------------------+
| name                 | dimension  | content                                                                         |
+======================+============+=================================================================================+
| myrownames           |            |                                                                                 |
+----------------------+------------+---------------------------------------------------------------------------------+
| no                   |            |                                                                                 |
+----------------------+------------+---------------------------------------------------------------------------------+
| xal                  | µg/L       |                                                                                 |
+----------------------+------------+---------------------------------------------------------------------------------+
| xca                  | mg/L       |                                                                                 |
+----------------------+------------+---------------------------------------------------------------------------------+
| xcl                  | mg/L       |                                                                                 |
+----------------------+------------+---------------------------------------------------------------------------------+
| xfe                  | mg/L       |                                                                                 |
+----------------------+------------+---------------------------------------------------------------------------------+
| xhv                  | mg/L       |                                                                                 |
+----------------------+------------+---------------------------------------------------------------------------------+
| xk                   | mg/L       |                                                                                 |
+----------------------+------------+---------------------------------------------------------------------------------+
| xmg                  | mg/L       |                                                                                 |
+----------------------+------------+---------------------------------------------------------------------------------+
| xmn                  | mg/L       |                                                                                 |
+----------------------+------------+---------------------------------------------------------------------------------+
| xna                  | mg/L       |                                                                                 |
+----------------------+------------+---------------------------------------------------------------------------------+
| xnh4                 | mg/L       |                                                                                 |
+----------------------+------------+---------------------------------------------------------------------------------+
| xno3                 | mg/L       |                                                                                 |
+----------------------+------------+---------------------------------------------------------------------------------+
| xpo4                 | mg P/L     |                                                                                 |
+----------------------+------------+---------------------------------------------------------------------------------+
| xso4                 | mg/L       |                                                                                 |
+----------------------+------------+---------------------------------------------------------------------------------+
| xzn                  | mg/L       |                                                                                 |
+----------------------+------------+---------------------------------------------------------------------------------+
| xhco3                | mg/L       |                                                                                 |
+----------------------+------------+---------------------------------------------------------------------------------+
| xco3                 | mg/L       |                                                                                 |
+----------------------+------------+---------------------------------------------------------------------------------+
| k20meas              | µS/cm      |                                                                                 |
+----------------------+------------+---------------------------------------------------------------------------------+
| k20                  | µS/cm      |                                                                                 |
+----------------------+------------+---------------------------------------------------------------------------------+
| orderK20             |            |                                                                                 |
+----------------------+------------+---------------------------------------------------------------------------------+
| hco3                 | meq/L      |                                                                                 |
+----------------------+------------+---------------------------------------------------------------------------------+
| cl                   | meq/L      |                                                                                 |
+----------------------+------------+---------------------------------------------------------------------------------+
| so4                  | meq/L      |                                                                                 |
+----------------------+------------+---------------------------------------------------------------------------------+
| no3                  | meq/L      |                                                                                 |
+----------------------+------------+---------------------------------------------------------------------------------+
| co3                  | meq/L      |                                                                                 |
+----------------------+------------+---------------------------------------------------------------------------------+
| h3o                  | meq/L      |                                                                                 |
+----------------------+------------+---------------------------------------------------------------------------------+
| na                   | meq/L      |                                                                                 |
+----------------------+------------+---------------------------------------------------------------------------------+
| k                    | meq/L      |                                                                                 |
+----------------------+------------+---------------------------------------------------------------------------------+
| ca                   | meq/L      |                                                                                 |
+----------------------+------------+---------------------------------------------------------------------------------+
| mg                   | meq/L      |                                                                                 |
+----------------------+------------+---------------------------------------------------------------------------------+
| nh4                  | meq/L      |                                                                                 |
+----------------------+------------+---------------------------------------------------------------------------------+
| fe                   | meq/L      |                                                                                 |
+----------------------+------------+---------------------------------------------------------------------------------+
| mn                   | meq/L      |                                                                                 |
+----------------------+------------+---------------------------------------------------------------------------------+
| al                   | meq/L      |                                                                                 |
+----------------------+------------+---------------------------------------------------------------------------------+
| zn                   | meq/L      |                                                                                 |
+----------------------+------------+---------------------------------------------------------------------------------+
| po4                  | meq/L      |                                                                                 |
+----------------------+------------+---------------------------------------------------------------------------------+
| pos                  | meq/L      | positive ions                                                                   |
+----------------------+------------+---------------------------------------------------------------------------------+
| neg                  | meq/L      | negative ions                                                                   |
+----------------------+------------+---------------------------------------------------------------------------------+
| ib                   |            | ion balance                                                                     |
+----------------------+------------+---------------------------------------------------------------------------------+
| oh                   | meq/L      |                                                                                 |
+----------------------+------------+---------------------------------------------------------------------------------+
| mu                   |            | parameter needed to select the method                                           |
+----------------------+------------+---------------------------------------------------------------------------------+
| sqmu                 |            | parameter needed to select the method                                           |
+----------------------+------------+---------------------------------------------------------------------------------+
| gam2                 |            | parameter needed to select the method                                           |
+----------------------+------------+---------------------------------------------------------------------------------+
| san                  | meq/L      | sum anions                                                                      |
+----------------------+------------+---------------------------------------------------------------------------------+
| skat                 | meq/L      | sum kations                                                                     |
+----------------------+------------+---------------------------------------------------------------------------------+
| alM                  |            | parameter needed to select the method                                           |
+----------------------+------------+---------------------------------------------------------------------------------+
| so4M                 |            | parameter needed to select the method                                           |
+----------------------+------------+---------------------------------------------------------------------------------+
| DO                   |            | parameter needed to select the method                                           |
+----------------------+------------+---------------------------------------------------------------------------------+
| tmp                  |            | parameter needed to select the method                                           |
+----------------------+------------+---------------------------------------------------------------------------------+
| also4                |            | parameter needed to select the method                                           |
+----------------------+------------+---------------------------------------------------------------------------------+
| alF                  |            | parameter needed to select the method                                           |
+----------------------+------------+---------------------------------------------------------------------------------+
| aloh                 |            | parameter needed to select the method                                           |
+----------------------+------------+---------------------------------------------------------------------------------+
| aloh2                |            | parameter needed to select the method                                           |
+----------------------+------------+---------------------------------------------------------------------------------+
| alZ                  |            | parameter needed to select the method                                           |
+----------------------+------------+---------------------------------------------------------------------------------+
| san2                 | meq/L      | sum anions corrected                                                            |
+----------------------+------------+---------------------------------------------------------------------------------+
| skat2                | meq/L      | sum cations corrected                                                           |
+----------------------+------------+---------------------------------------------------------------------------------+
| sgem                 | meq/L      | (san2+skat2)/2                                                                  |
+----------------------+------------+---------------------------------------------------------------------------------+
| rcl                  |            | parameter needed to select the method                                           |
+----------------------+------------+---------------------------------------------------------------------------------+
| rhco3                |            | parameter needed to select the method                                           |
+----------------------+------------+---------------------------------------------------------------------------------+
| rso4                 |            | parameter needed to select the method                                           |
+----------------------+------------+---------------------------------------------------------------------------------+
| rno3                 |            | parameter needed to select the method                                           |
+----------------------+------------+---------------------------------------------------------------------------------+
| meth                 |            | method used like McNeal, Dunlap etc.                                            |
+----------------------+------------+---------------------------------------------------------------------------------+
| meth\_               |            | sub method used                                                                 |
+----------------------+------------+---------------------------------------------------------------------------------+
| rk20                 | µS/cm      | calculated conductivity at 20°C                                                 |
+----------------------+------------+---------------------------------------------------------------------------------+
| ec25                 | mS/m       | calculated conductivity at 25°C                                                 |
+----------------------+------------+---------------------------------------------------------------------------------+
| xecv                 | mS/m       | measured conductivity at 25°C                                                   |
+----------------------+------------+---------------------------------------------------------------------------------+
| ec25_xecv_sr         |            | standard residues of log transformed calculated and measured conductivity       |
+----------------------+------------+---------------------------------------------------------------------------------+
| pxecv                |            | transformation of xecv to calculate prinslabel                                  |
+----------------------+------------+---------------------------------------------------------------------------------+
| pec25                |            | transformation of ec25 to calculate prinslabel                                  |
+----------------------+------------+---------------------------------------------------------------------------------+
| prinslabel           |            | indicates whether the calculated conductivity does not match the measured value |
+----------------------+------------+---------------------------------------------------------------------------------+
| percentage_xecv_ec25 |            | percentage difference between measured and calculated conductivity              |
+----------------------+------------+---------------------------------------------------------------------------------+
| skat_san_sr          |            | standard residues of log transformed sum of kations or anions                   |
+----------------------+------------+---------------------------------------------------------------------------------+
| max_anion            | meq/L      |                                                                                 |
+----------------------+------------+---------------------------------------------------------------------------------+
| max_anion_name       |            | anion with the highest milliequivalents per liter                               |
+----------------------+------------+---------------------------------------------------------------------------------+
| max_kation           | meq/L      |                                                                                 |
+----------------------+------------+---------------------------------------------------------------------------------+
| max_kation_name      |            | kation with the highest milliequivalents per liter                              |
+----------------------+------------+---------------------------------------------------------------------------------+
| suspect              |            | none or max_anion or max_kation                                                 |
+----------------------+------------+---------------------------------------------------------------------------------+
| percentage           |            | difference between script Stuyfzand and this script in %                        |
+----------------------+------------+---------------------------------------------------------------------------------+
|                      |            |                                                                                 |
+----------------------+------------+---------------------------------------------------------------------------------+

: Output headings

The data generally have a logarithmically transformed normal distribution. The higher values show higher differences but the relative differences remain constant at higher values. For example duplicate measurements may have a 10% error over a wide range of concentrations. The value of standard residues of log transformed data shows whether the data really deviate. 95% of the data fall between -2 and +2. When ec25_xecv_sr \> 2 the calculated conductivity is much higher than the measured one. When the skat_san_sr \< (-2) there is an excess of anions. When the calculated conductivity is much higher than the measured one and the ion balance has an excess of anions, then the anion with the maximum concentration of milli-equivalents is suspect.

## Output style Stuyfzand

The output style Stuyfzand is a specialized output style to compare the results of the calculated conductivity k20 from the report of Stuyfzand with the calculated conductivity rk20 in this groundwaterconductivity::calculate_conductivity.R script. Both are expressed in micro Siemens/centimeter at 20°C. The percentage column is calculated as 100\*(rk20-k20)/k20 and rounded to zero digits. In the file with_calculated_conductivity.rda the comparison between the report of Stuyfzand and our script is shown. Generally the difference is less than 2% except for row 3, row 5 and row 7 where it is 5%, 45 and 8%. These three rows use the first method of Rossum and have very low conductivities . The five other rows using this method gave much more accurate results.

## Output style minimal

The minimal output style is a selection of the with_all_calculated_conductivity.rda with the input values in milligrams/liter as in table 1 LMM style (xcl to xzn). A selected minimal number of output headings is shown with the dimensions expressed in table 2. The output is again saved as with_calculated_conductivity.rda

## Add bicarbonate

The bicarbonate anion is in equilibrium with CO₂ gas from the air. It therefore can escape from sampling through the air. At the LMM monitoring network we have chosen not to sample bicarbonate. In that case the bicarbonate concentration can only be roughly estimated from the ion balance when one assumes that there are equal charge equivalents from cations and anions. In that case the amount of milli-equivalents of bicarbonate is equal to the sum of the cations minus the sum of the anions. This can only be performed when there is an excess of cations. For the data control this is not beneficial since we do not actually know the ion balance anymore when there is an excess of cations. Nevertheless when there is an excess of anions the ion balance is still useful and the major anion might be suspect when the calculated conductivity ec25 exceeds the measured conductivity xecv. The input style broadLMM will not have xhco3 and will perform this estimation of bicarbonate.

## Add phosphate

In the Dutch groundwater monitoring network xpo4 is not measured, instead it is assumed that phosphate is equal to total phosphorus. Since total phosphorus xptot and xpo4 are both expressed in mg P/liter the xpo4 can easily be estimated from xptot. The input style broadLGW will have xptot instead of xpo4 and will perform this replacement.
